### ISSUE TITLE
certificate issue at go.opencensus.io

### ISSUE THREAD

**Issue by caselongo** [googleapis/google-cloud-go#11481]
The bigquery and some other packages do not build because of a certificate issue at go.opencensus.io, see below.
Excuse in advance if this is not the right place to report.

go.opencensus.io@v0.24.0: unrecognized import path "go.opencensus.io": https fetch: Get "https://go.opencensus.io/?go-get=1": tls: failed to verify certificate: x509: certificate has expired or is not yet valid:

**Comment by codyoss** [comment]
I will look into seeing if there is something we can do here, but I am not sure off the top of my head.

**Comment by codyoss** [comment]
I think this issue seems resolved now, please confirm

**Comment by caselongo** [comment]
I have still the same issue. 

 downloading go.opencensus.io v0.24.0
..\..\..\..\pkg\mod\cloud.google.com\go\auth@v0.9.3\grpctransport\grpctransport.go:30:2: unrecognized import path "go.opencensus.io": https fetch: Get "https://go.opencensus.io/?go-get=1": tls: failed to verify certificate: x50

If you go here manually you see the certificate issue as well: https://go.opencensus.io/?go-get=1

**Comment by codyoss** [comment]
What is your GOPROXY setting? I suggest using the default of `GOPROXY='https://proxy.golang.org,direct'` to help avoid this issue for now.

**Comment by cartermckinnon** [comment]
I must use `GOPROXY=direct`, and this library is currently unusable because of its dependency on `go.opencensus.io` (which is archived and unmaintained).

The `storage` module of this project is used downstream in Kubernetes, which is causing further impact (see the linked issues above). Do the maintainers here have any options to resolve the issue? Can this dependency be removed/replaced?

**Comment by codyoss** [comment]
We will further investigate what we can do to help here. Thanks for the extra info @cartermckinnon, I was unaware of any downstream impact.

**Comment by dashpole** [comment]
go.opencensus.io should be fixed now

**Comment by codyoss** [comment]
Thanks for the update @dashpole!
