### ISSUE TITLE
datastore: *Client.RunAggregationQuery() panics

### ISSUE THREAD

**Issue by MarioGravel** [googleapis/google-cloud-go#7800]
**Client**

datastore

**Environment**

Cloud Run

**Go Environment**

$ go version
go version go1.19.7 windows/amd64

$ go env
set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\xxxxxxxx\AppData\Local\go-build
set GOENV=C:\Users\xxxxxxxx\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMODCACHE=C:\Users\xxxxxxxx\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\xxxxxxxx\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.19.7
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=D:\xxxxxxxx\go.mod
set GOWORK=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=C:\Users\xxxxxxxx\AppData\Local\Temp\go-build961903078=/tmp/go-build -gno-record-gcc-switches

**Code**

```go
func GetCrowdSizeByRoom(dsClient *datastore.Client, room *Room) int {
	query := datastore.NewQuery("Human").FilterField("Room", "=", room.Key).NewAggregationQuery().WithCount("Size")
        // Next line panics
	size, err := dsClient.RunAggregationQuery(context.Background(), query)
	if err != nil {
		log.Printf("error when counting crowd : %v", err)
		return 0
	}

	...

}
```

**Expected behavior**

This code, or something similar, is missing from `cloud.google.com/go/datastore/client.go`

```go
func (dc *datastoreClient) RunAggregationQuery(ctx context.Context, in *pb.RunAggregationQueryRequest, opts ...grpc.CallOption) (res *pb.RunAggregationQueryResponse, err error) {
	ctx = trace.StartSpan(ctx, "cloud.google.com/go/datastore.datastoreClient.RunAggregationQuery")
	defer func() { trace.EndSpan(ctx, err) }()

	err = dc.invoke(ctx, func(ctx context.Context) error {
		res, err = dc.c.RunAggregationQuery(ctx, in, opts...)
		return err
	})
	return res, nil
}
```

**Actual behavior**

The code panic at line `789` of `cloud.google.com/go/datastore/client.go`

**Screenshots**

Line `789` is calling `RunAggregationQuery` on `c.client` but it doesn't implement this part of the interface `DatastoreClient` from `google.golang.org/genproto/googleapis/datastore/v1/datastore.pb.go`
![image](https://user-images.githubusercontent.com/14111466/233260949-d6e7d8a6-a6eb-4409-b472-fb0f8ba99acd.png)

**Additional context**

`datastore.Client.Count()` works but it is deprecated.

**Comment by MarioGravel** [comment]
Also, to be able to do something with the `AggregationResult`, something like this is required in `cloud.google.com/go/datastore/query.go` starting at line `794`
```go
	ar := make(AggregationResult)

	// TODO(developer): change batch parsing logic if other aggregations are supported.
	for _, a := range res.Batch.AggregationResults {
		for k, v := range a.AggregateProperties {
			switch v.ValueType.(type) {
			case *pb.Value_NullValue: ar[k] = v.GetNullValue()
			case *pb.Value_BooleanValue: ar[k] = v.GetBooleanValue()
			case *pb.Value_IntegerValue: ar[k] = v.GetIntegerValue()
			case *pb.Value_DoubleValue: ar[k] = v.GetDoubleValue()
			case *pb.Value_TimestampValue: ar[k] = v.GetTimestampValue()
			case *pb.Value_KeyValue: ar[k] = v.GetKeyValue()
			case *pb.Value_StringValue: ar[k] = v.GetStringValue()
			case *pb.Value_BlobValue: ar[k] = v.GetBlobValue()
			case *pb.Value_GeoPointValue: ar[k] = v.GetGeoPointValue()
			case *pb.Value_EntityValue: ar[k] = v.GetEntityValue()
			case  *pb.Value_ArrayValue: ar[k] = v.GetArrayValue()
			default:
				ar[k] = v
			}
		}
	}
```

Then, I'm able to complete my program
```go
func GetCrowdSizeByRoom(dsClient *datastore.Client, room *Room) int64 {
	query := datastore.NewQuery("Human").FilterField("Room", "=", room.Key).NewAggregationQuery().WithCount("Size")
	size, err := dsClient.RunAggregationQuery(context.Background(), query)
	if err != nil {
		log.Printf("error when counting crowd : %v", err)
		return 0
	}
	if crowdSize, ok := size["Size"]; ok {
		return crowdSize.(int64)
	}
	return 0
}
```

It is tested locally and it works.

**Comment by alon-ne** [comment]
Hi, I'm also encountering this issue. Panic at line 789 just like @MarioGravel saw

**Comment by trifox** [comment]
hi, we encountered this issue as well

**Comment by marwansalem** [comment]
I have this issue as well, is this fixed?

**Comment by triplequark** [comment]
> I have this issue as well, is this fixed?

A fix is being prepared. ETA 2 weeks.

**Comment by bhshkh** [comment]
The fix is available in datastore 1.12.0

**Comment by alon-ne** [comment]
still getting a panic with version 1.12.0... It's now in query.go line 797. Tested with datastore emulator

**Comment by alon-ne** [comment]
When testing with real datastore instead of the emulator, I see I get a (*datastore.Value) in the returned map, but that type is not exposed through the datastore package, how do I use it?

**Comment by bhshkh** [comment]
Sample usage:


`
import (
        ...
	"cloud.google.com/go/datastore"
	pb "google.golang.org/genproto/googleapis/datastore/v1"
)

func main() {
        ...
        ...
        ...
        countAlias := "count"
	query := datastore.NewQuery("City")
	aggQuery := query.NewAggregationQuery()
	aggQuery = aggQuery.WithCount(countAlias)
	aggResult, _ := client.RunAggregationQuery(ctx, aggQuery)
	count := aggResult[countAlias]
	pbVal := count.(*pb.Value)
	intVal := pbVal.GetIntegerValue()
	fmt.Printf("Count is %v", intVal)
	
}
`

**Comment by enocom** [comment]
@bajajneha27 shall we put that example usage into the docs?

**Comment by alon-ne** [comment]
update: now I see the emulator gives me a more friendly message:
```rpc error: code = Unimplemented desc = Method google.datastore.v1.Datastore/RunAggregationQuery is unimplemented```
Any ETA on when the datastore emulator will support aggregation queries? I don't feel comfortable releasing this to production without testing it in the emulator first. 
Thanks

**Comment by alon-ne** [comment]
Any update about emulator support?
