### ISSUE TITLE
spanner: cannot find module providing package cel.dev/expr

### ISSUE THREAD

**Issue by LeVadim** [googleapis/google-cloud-go#9031]
**Client**

Spanner

**Environment**

Local OSX Sillicon 

**Go Environment**

$ go version
go version - go1.21.4 darwin/arm64

$ go env
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/Macbook/Library/Caches/go-build'
GOENV='/Users/Macbook/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/Macbook/go/pkg/mod'
GONOPROXY='github.com/...'
GONOSUMDB='github.com/...'
GOOS='darwin'
GOPATH='/Users/Macbook/go'
GOPRIVATE='github.com/...'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/Macbook/...'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/dm/zy86pnt94t10jbc9q8_1scg00000gp/T/go-build556399722=/tmp/go-build -gno-record-gcc-switches -fno-common'

**Code**
go get -u cloud.google.com/go/spanner

go: downloading github.com/googleapis/gax-go v1.0.3
go: downloading github.com/cncf/xds v0.0.0-20231117232044-0f5e0d9dbc12
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/cncf/udpa v0.0.1
go: cloud.google.com/go/spanner imports
        google.golang.org/grpc/xds/googledirectpath imports
        google.golang.org/grpc/xds imports
        google.golang.org/grpc/xds/internal/xdsclient/xdslbregistry/converter imports
        github.com/cncf/xds/go/xds/type/v3 imports
        cel.dev/expr: cannot find module providing package cel.dev/expr

go mod tidy gives the same error

**Expected behavior**
The download or go mod tidy would work without errors

**Actual behavior**
It crashes with errror:         cel.dev/expr: cannot find module providing package cel.dev/expr

**Screenshots**
![Screenshot 2023-11-18 at 2 57 36 PM](https://github.com/googleapis/google-cloud-go/assets/16689198/cb0885ba-c33e-4a46-ab36-fdc42b3167de)

**Comment by LeVadim** [comment]
@arhea Helped under linked github issue

Solution to add this replace statement helped

`replace github.com/cncf/xds => github.com/cncf/xds v0.0.0-20231116142803-3a472e524827`

**Comment by arhea** [comment]
*Temporary fix that reverts the previous version. Once https://github.com/cncf/xds/issues/76 is fixed, this should be removed. Looks like it is just a problem with the `cel.dev` domain which I'm sure will get fixed soon.

**Comment by sergiitk** [comment]
Yes, CEL folks are working on it: https://github.com/cncf/xds/issues/76#issuecomment-1819872696

**Comment by sergiitk** [comment]
FYI - the change that caused https://github.com/cncf/xds/issues/76 has been rolled back in https://github.com/cncf/xds/pull/79 until the CEL team fixes the domain settings.

**Comment by noahdietz** [comment]
@sergiitk I'm just here triaging bugs, will this be fixed with a new `xds` release/dependency update?

**Comment by rahul2393** [comment]
[sergiitk](https://github.com/sergiitk) Is it still happening? 
If not please help closing the ticket.

**Comment by sergiitk** [comment]
Yes, this is still happening. I had a chat with CEL folks this week, they're close to rolling out the domain settings with necessary redirects.

**Comment by sergiitk** [comment]
The fix: https://github.com/cncf/xds/pull/89.

**Comment by sergiitk** [comment]
FYI The fix has been merged. @rahul2393 feel free to close this one.
